### PR TITLE
RABSW-1128: Only fake out clientmounts on compute nodes in kind

### PR DESCRIPTION
**Pull request by matthew-richerson**
When running in kind, the rabbit nodes have a separate clientmount controller in the nnf-sos code that handles fake Rabbit mounts.

Signed-off-by: Matt Richerson <matthew.richerson@hpe.com>

### CODE REVIEW

**Comment by NateThornton** [comment]
I'm a bit confused about this one. You removed the conditional check - so aren't you faking out client mounts for both Kind and Test? Maybe the title is wrong? For completeness, should we rename `filterByNonRabbitNamespacePrefixForTest` to just `filterByNonRabbitNamespacePrefix`?

**Comment by matthew-richerson** [comment]
> I'm a bit confused about this one. You removed the conditional check - so aren't you faking out client mounts for both Kind and Test? Maybe the title is wrong? For completeness, should we rename `filterByNonRabbitNamespacePrefixForTest` to just `filterByNonRabbitNamespacePrefix`?

I'll change the name to remove the "ForTest". The PR title is ambiguous. It's supposed to mean "Only fake out client mounts on compute nodes (instead of compute nodes and rabbit nodes) in kind"

**Comment by bdevcich-hpe** [comment]
What does fake out mean in this sense? 

> It's supposed to mean "Only fake out client mounts on compute nodes (instead of compute nodes and rabbit nodes) in kind"

What does "fake out" mean in this sense? For containers, I want a fake mount on the rabbit node so I can mount that as a volume into the container. This change supports that, right?

**Comment by matthew-richerson** [comment]
> What does fake out mean in this sense?
> 
> > It's supposed to mean "Only fake out client mounts on compute nodes (instead of compute nodes and rabbit nodes) in kind"
> 
> What does "fake out" mean in this sense? For containers, I want a fake mount on the rabbit node so I can mount that as a volume into the container. This change supports that, right?

Yes, this is part of that change. Before this change, all ClientMounts in kind were handled by a reconciler in dws that would make the ClientMount as ready. Now there is a separate ClientMount reconciler in nnf-sos that handles the ClientMounts for the Rabbit nodes and creates the empty directories. This change is to exclude the ClientMounts for Rabbit nodes in the dws reconciler since they're being handled by nnf-sos. ClientMounts for compute nodes are still handled by the dws reconciler.

**Comment by bdevcich-hpe** [comment]
Thanks for the clarification.

**Review by bdevcich-hpe — APPROVED** [review]

**Pull request merged**
